### ISSUE TITLE
`setShouldRenderCallback` only returns true for animations

### ISSUE THREAD

**Issue by OhadRau** [revery-ui/revery#170]
Currently, `setShouldRenderCallback` returns true only when there's an animation changing. However, there's other situations where it should always re-render, such as a style changing, an event happening, or a node's children/parent being updated. The program should also re-render whenever it loses focus, since windows overlapping over the draw area won't get cleared after they're moved (see image in #152). Furthermore, changing the callback doesn't seem to work (can't figure out why, but if you take Akin's example code and add `Window.setShouldRenderCallback(w, () => true);` it doesn't change the result). 

Regardless, we need a better metric for deciding when to re-render elements going forward as this can cause a lot of confusion to the user. One way to do this while keeping performance is to only re-render certain elements, marking them for re-rendering based on some of the events stated above (event, style change, parent/child change, & window losing focus. We might also need to take state changes into account).

**Comment by bryphe** [comment]
Ah I've been meaning to fix this for a while... sorry @Akin909 and @OhadRau that you hit this! Thanks for the detailed report and investigation. I put some details in #171 on how I was looking at a fix.

> Regardless, we need a better metric for deciding when to re-render elements going forward as this can cause a lot of confusion to the user. 

Definitely! We don't want the user or developer to need to think about this. Should be handled completely by the framework 👍 

> One way to do this while keeping performance is to only re-render certain elements, marking them for re-rendering based on some of the events stated above (event, style change, parent/child change, & window losing focus.

This would be great! It will be more complicated, though. A simple approach would be to just clear the section of the screen the node takes up, and draw there - but this will break in cases of a transparent node. Alternatively, #54 would mean we could render complex elements to their own 'render texture' - so we'd only need to re-render up to the first render texture, and then do a final composition pass. But this could save rendering because we wouldn't need to re-render the whole scene.
