### ISSUE TITLE
Border styles cause incorrect layout and hitTest

### ISSUE THREAD

**Issue by bmathews** [revery-ui/revery#175]
With a 50px border (orange) added to the button element, it is no longer centered correctly in the flex layout, and the inner contents (white) of the element expand unexpectedly. 

![image](https://user-images.githubusercontent.com/848347/50603723-51063c80-0e70-11e9-8908-a63d548908d0.png)

Example repo:
https://github.com/revery-ui/revery/compare/master...bmathews:clickable-styles?expand=1

**Comment by OhadRau** [comment]
Hmm, I'm looking into this since but I'm still a bit confused by why this is happening. We definitely are applying the world transform to the mouse position in `hitTest`, which is basically what gets done to children to adjust their position as far as I know. What is probably happening here is that the internal world transform is different from the one given to the node's children, so we need to adjust that manually (i.e. calculate the border sizes).

In terms of  it not being centered, I'm thinking this might be a bug in Flex. We don't do anything in Revery to calculate how the layout and all the border info should be passed into Flex to calculate, which makes me think it must be something in Flex. In this file, it looks like the axis of the border is calculated, but the width is never used in this: https://github.com/jordwalke/flex/blob/master/src/lib/Layout.re#L347. This was a really quick scan through the code though so I'm honestly not sure.

Will keep you posted as I investigate this

**Comment by OhadRau** [comment]
Actually, I just thought about this again and I bet I know what's wrong. Rather than a translation, this should be shrinking the borders to fit into the width. Gonna try that now

**Comment by OhadRau** [comment]
@bmathews Should be fixed as soon as #177 is merged. Thanks for finding this!
