### ISSUE TITLE
Add ability to query a style from a list of styles

### ISSUE THREAD

**Issue by Akin909** [revery-ui/revery#239]
This would be particularly helpful for building native components e.g. if a user passes a list of styles like
```reason
<Slider
 style=Style.[color(red)]
/>
```
and you wanted to query this in the component so you could do some logic on basis of a value a user has passed in, I'm working on an `unwrap`
function which allows you to get the raw value a user passed in since
as it actually comes down it would be wrapped in `Color(red)`

**Comment by Akin909** [comment]
This involves trying to pull a specific polymorphic variant out of a list and unpacking its value :worried:

**Comment by Akin909** [comment]
@OhadRau have been wrangling trying to get something like the first example so it's good to know (side note where can I find out more about *why* or rather how it does work so I can avoid such rabbit holes in the future)

re the solution you proposed @bryphe mentioned something similar in #256 (I think) and the TLDR is that a `Style.t` is a strict type and so creating one means also filling in all the blanks, some of the properties don't accept `cssUndefined` though so I'd have to set some values like in the case of our defaults so if you tried to see for example if `Style.unwrap(position)` or something you would always get a value but you wouldn't know if it was a default value or what the user set

**Comment by Akin909** [comment]
not entirely sure if you were suggesting writing the values to a record actually but we I did consider creating an unwrap function for all the various types since the second snippet with the fold works, it just seemed very repetitive so been trying to figure out if there is a more generalizable solution

**Comment by OhadRau** [comment]
> have been wrangling trying to get something like the first example so it's good to know (side note where can I find out more about why or rather how it does work so I can avoid such rabbit holes in the future)

Hmm not sure if I have a specific link, but that's something I spent ages trying to figure out in an old project. Essentially, there's no way to tell the type system that the constructor \`X goes with \`X(int), so we can't do something like `select(`X, [`X(0), `Y(1)])`. I believe the workaround used by the project I was looking at (OCaml FuSe) was to let the function construct an `X with a dummy value:

```
select(x => `X(x), [`X(0), `Y(1)])
```
which would allow comparison if you did:
```
switch (style) {
  `X(x) => `X(x) == f(x) /* f is x => `X(x) */
}
```
Note: This still requires us to enumerate every case.

The other issue with this was that there was no way to get it to return the actual result, since you can't access the type of that constructor. So there's no way to tell the compiler:
```
let x: [`X('a)] => 'a
```
Since it doesn't allow type variables in that spot (if it did, we'd still want to be generic over the ``X` which wouldn't work, since there's no syntax for that).

Finally, the last problem is that OCaml doesn't have dependent typing, which means types cannot depend on values. For the type [\`A(int) | \`B(string)] we'd want the return type of the unwrap function to depend on whether it's an \`A style or a \`B style. There's probably a couple of workarounds to this, but all of them would get kind of ugly as we tried to scale up this library.
