### ISSUE TITLE
Error: No sandbox found (from . and up)

### ISSUE THREAD

**Issue by ghostslayer989** [revery-ui/revery#285]
On Native windows if I try to run any esy command as admin I get "error: No sandbox found (from . and up)"

**Comment by bryphe** [comment]
@ghostslayer989  - hmm, can you give us some more info?

- What version of Windows?
- Which shell are you using - `cmd`, `powershell`, etc?
- Which `esy` version?

In addition, can you please share out some verbose logs? You can get these by setting `ESY__LOG` to `debug` - that might help us narrow down the issue! cc @andreypopp too

Thanks!

**Comment by ghostslayer989** [comment]
Windows 10 1809 

CMD: ADMIN

ESY: 0.4.10

Same message if I do --verbosity debug.

**Comment by ghostslayer989** [comment]
Hello?

**Comment by OhadRau** [comment]
I think the reason for this may be related to OPAM. For me, I was having trouble getting OPAM 2.0 to work on Windows because it couldn't create sandboxes. The way I fixed it was disabling sandboxing in OPAM. However, I didn't have to do that in my CMD so I'm not sure why it's not working for you. Mind sharing how you installed `esy`? I believe I simply did `npm install -g esy` and it worked out of the box

**Comment by OhadRau** [comment]
Actually, I get the same error when running `esy` outside of the project directory:

![image](https://user-images.githubusercontent.com/9326698/52082735-94d18c00-256b-11e9-9cb8-67c6692c1dab.png)

Are you sure you're running `esy` in the correct project directory?
