### ISSUE TITLE
Performance (Memory): Add eviction to Memoize functionality

### ISSUE THREAD

**Issue by bryphe** [revery-ui/revery#333]
We aggressively memoize expensive computations using a very simple `Memoize.make` helper function: 
https://github.com/revery-ui/revery/blob/ed0f2d92c4b0e0f84f61ef35aebac5690fc76e4b/src/Core/Revery_Core.re#L32

Some examples of items we currently 'memoize' today:
- Geometry: https://github.com/revery-ui/revery/blob/7b8ccf7e9644d22359d512331bdcb4b63762fecd/src/UI/Assets.re#L15
- Font glyph rendering: https://github.com/revery-ui/revery/blob/3516ca529eb0e85e7c1063578f3567c48be1ab59/src/UI/FontRenderer.re#L7
- Font shaping: https://github.com/revery-ui/revery/blob/3516ca529eb0e85e7c1063578f3567c48be1ab59/src/UI/FontRenderer.re#L44

For very expensive operations that aren't meant to be done frame-over-frame, this is helpful - and keeps us from wasting cycles.

However, it also causes our memory usage to balloon - and eventually, we really don't need to keep some of these items around.

We should implement some sort of __eviction policy__ so that we can remove items that aren't being used.

One option for this would be some sort of least-recently-used eviction policy - it looks like there are some LRU cache implementations like:  [`lru-cache`](https://opam.ocaml.org/packages/lru-cache/)

The work here would be to investigate some sort of eviction policy to be used to augment (or, perhaps an lru cache could replace entirely) our `Memoize.make` functionality.

**Comment by jchavarri** [comment]
One of the most interesting memoization techniques that I've learnt in JavaScript is the usage of [`WeakMap`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) to store the result from expensive computations in a map where the keys are weakly hold. The advantage of weak maps is that once the key K is not hold anymore anywhere in the program, any key/value pair in the weak map with key === K is released as well, without any manual handling required.

The upside compared to lru-cache or other strong memoization techniques is that weak memoization can be very effective, allocating and liberating memory in a very "elastic" way. The main downside compared to lru-cache is that the costs in memory have no hard upper limit, so if new values keep arriving to a memoized function, new results keep being allocated, so overuse of weak memoization can lead to too much allocation of data that might end up not being very actively needed during the program execution.

But I still think weak memoization might be a good fit for the kind of programs built with a React-based renderer like Revery, and a language based on immutability like Reason, because references are not generally hold for too long. With the usual disclaimer of "use with care when it makes sense" 😄 

I just found out that WeakMaps in JavaScript were actually built on the idea of something called "ephemeron" (see [this great example](https://twitter.com/BrendanEich/status/1000472997969281024) by Brendan Eich on Twitter), which were discovered in 1997 ([paper](https://www.researchgate.net/publication/221320677_Ephemerons_A_New_Finalization_Mechanism)) and also seems were added to OCaml in 4.03! 🎉  (see [JaneSt blog post](https://blog.janestreet.com/ocaml-4-03-everything-else/) where ephemerons are explicitly mentioned).

@bryphe I have no idea about ephemerons in OCaml tbh 😅  but it seems something worth exploring, maybe for just a small set of the cases mentioned above?

**Comment by jchavarri** [comment]
The OCaml docs about ephemeron are great too: https://caml.inria.fr/pub/docs/manual-ocaml/libref/Ephemeron.html

**Comment by bryphe** [comment]
Wow, nice find @jchavarri ! You weren't kidding - the description for the `Ephemeron` module's use case reads exactly like the problem we're trying to solve. Seems promising!

We might have to evaluate the way we're using the keys (we're using transient tuples as keys - probably not an ideal approach in general, but especially not in the context of this module). 

In some cases we're using keys like `(fontFace: FontKit.fk_face, fontSize: int, glyphId: int`) to memoize `renderGlyph` - I wonder how that would work in the context of a WeakMap - the fontFace would likely be long-lived, so it might mean that the values are long-lived too? We'd potentially have to tag it with another key (perhaps a render `node` instance?) to tie it into some shorter-lived lifecycle 🤔

**Comment by OhadRau** [comment]
I believe the key is evaluated as the whole thing, i.e. the lifetime of a key (a, b) is independent of the lifetime of (a, b) individually. This is good because we don't have to worry about things living too long, but might cause issues too since we have to start storing that value somewhere so that the key keeps existing. (All this is speculation though)

**Comment by Akin909** [comment]
I'd be curious to look into this if no one else is already poking around
