### ISSUE TITLE
UI - Input: Cursor should not shift text content

### ISSUE THREAD

**Issue by aweary** [revery-ui/revery#415]
![2019-03-25 16 02 02](https://user-images.githubusercontent.com/6886061/54969277-c72fb200-4f3a-11e9-9c3f-d695095a5ceb.gif)

The issue seems to be that the cursor `View` is part of the normal content flow, so when it moves it also shifts the characters around. I checked oni2 and it doesn't have this problem since it [uses absolute positioning for the cursor](https://github.com/onivim/oni2/blob/master/src/editor/UI/EditorSurface.re#L188-L216) and manually calculates the offset. It seems like something similar should be done here for the `Input` component.

**Comment by bryphe** [comment]
Thanks for the report & gif, @aweary! Confirmed on Windows - it seems like we're including the cursor in the text calculation (which is shifting the text).

**Comment by aweary** [comment]
@bryphe I’m happy to work on this if you can give a few code pointers to get started with 🙂

**Comment by Akin909** [comment]
Would be great to have some help with the input 😍, at the moment the cursor is in the flow which causes this issue. We began discussing some of the ongoing issues with the input in #203. Something we haven't done yet is expose a way of finding out where a character is in the text which would allow us able to position the cursor absolutely

**Comment by bryphe** [comment]
Definitely, would be awesome to have help @aweary ! 💯 

Some ideas for starting out - this code here is important:
https://github.com/revery-ui/revery/blob/41f97bdf5e878bedbc307a7bff21fdd38047d961/src/UI_Components/Input.re#L240

(This is where we split the text and put a cursor in the middle).

We actually have an API to measure text size here: https://github.com/revery-ui/revery/blob/41f97bdf5e878bedbc307a7bff21fdd38047d961/src/Draw/Text.re#L38

Instead of rendering the cursor 'in the flow' - we could measure the `startStr` with this API (getting the fontFamily/fontSize, and the text which we already have with `startStr) - this would give us the size of the string before the cursor in pixels. Then, we could render the cursor absolutely positioned, out of the flow, based on the width of that measurement.

This will get a bit more complicated in the case of multi-line text, but I believe our inputs only handle the single-line case (something we'll have to think about as we extend them to support multi-line!).

**Comment by bryphe** [comment]
Just a heads up @aweary - looks like @tatchi started this in #419 (don't want to duplicate work 😄 )
