### ISSUE TITLE
Display Scaling Support

### ISSUE THREAD

**Issue by CrossR** [revery-ui/revery#528]
Windows has the concept of scaling:

![image](https://user-images.githubusercontent.com/10038688/62149384-80403780-b2f3-11e9-8844-5c879453b508.png)

Which scales everything up, such that a high-resolution screen can be scaled to see things more clearly.

Since revery isn't currently respecting that, apps can look very different since they aren't scaled the same way that most other apps are.

It looks like GLFW 3.3 has more reliable ways of picking up DPI settings, so this should help here.
We should update GLFW, then investigate if any further updates are needed.

For reference, here is Oni2 on a 4K screen at 150% scaling: 

![image](https://user-images.githubusercontent.com/10038688/62149567-efb62700-b2f3-11e9-81e3-2be194ef6f11.png)

**Comment by garth** [comment]
I have the same issue on Linux with SwayWM (wayland). Except that Sway will attempt to scale the app, so it's not too small, but fonts are quite blurry.

**Comment by bryphe** [comment]
With the latest SDL2 work - we should have this fixed in Windows. We exposed a new API to get the Win32 scale factor, and pick that up in our scaling - so once this PR is in: https://github.com/revery-ui/revery/pull/555 - the situation on Windows should be improved.

We're also trying to have better behavior on Linux - by respecting the `GDK_SCALE` environment variable, and falling back to measuring DPI otherwise.

**Comment by CrossR** [comment]
I think the bulk of this can be considered complete now, and any follow up tasks can probably go under a less general issue.
