### ISSUE TITLE
Load image from absolute path/url

### ISSUE THREAD

**Issue by baransu** [revery-ui/revery#537]
Trying to display images from URL I found it's currently not supported. I decided to download images to some tmp directory and use an absolute path as an Image src. And that's also not supported right now: https://github.com/revery-ui/revery/blob/aa2051c7c6e562b0b13acd43ff4724e02067097f/src/Draw/ImageRenderer.re#L25

The best option would be to have:
```reason
type src = Url(string) | Relative(string) | Absolute(string)
```
which would allow loading images from `/assets`, any directory and URL.

I'm willing to help with that feature but I don't know what's the best approach to download image and use it as a texture in ImageRenderer.

**Comment by lessp** [comment]
Regarding `URL` I experimented a bit with this yesterday and got a PoC working. May be happy to take a stab at it, depending on what you are seeing!

My "get-something-running" approach was to save the images to a temporary folder, escape the url from any illegal characters and then provide that path to the renderer.

Some questions I had:

- Do we delete temporary cached images on application-close?
- Where do we store the temporary files? Might be platform-specific

There are probably other approaches which may be more suited, just leaving this here since I at least did some experimenting! 🙂

**Comment by Et7f3** [comment]
Maybe let the user decide with `Url(string, option(string))` and the second argument if `None` mean non-cached and `Some(cachedPath)` mean to save file to `cachedPath`. And provide cleaning functions:  `cleanAll`, `cleanOneFile`.
