### ISSUE TITLE
How to render an array of components by iterating over a List

### ISSUE THREAD

**Issue by TrakBit** [revery-ui/revery#559]
I am working on creating a table component for revery but can't figure out. This approach doesn't seem to work

```
 let views = [1, 2, 3]
 let v = () => </View>;
 (List.iter(v, views))
```

**Comment by Et7f3** [comment]
Ok some error.
- To have self closing element we have to put the salsh at the end like normal HTML.
`</View>` => `<View/>`
- Also the function v take unit `()` it won't magically render what you want.
`let v = ()` => `let v = i`
- You have used iter instead of map: you want to generate a new list from the first one.
`List.iter(v, views)` => `List.map(v, views)`
- Then you have a list of `React.syntheticElement`. One common way to convert `list(React.syntheticElement)` =>`React.syntheticElement` is to wrap with a View component. Like this `(List.map(v, views))` => `<View>...(List.map(v, views))</View>`
You may notice `</View>` because here it is not a self-closing element: it is a end tag. The syntax follow the HTML one. It is called JSX.
- So here we have 3 views. We want to have contente inside we will fix the v function
`let v = i => </View/>;` =>
```
let style =
  Style.[
    fontSize(20),
    fontFamily("Roboto-Regular.ttf"),
  ];
  let v = i => <View><Text style=style text="Hellow world"></Text></View>;
```
We have to put some font: in the future we will auto-detect font available. One feature of reason is `style=style` => `style` the shortcut is valid only if it is the same name.
- now simply use the valeur of `v`
`<Text style=style text="Hellow world"></Text>` => `<Text style=style text=string_of_int(i)></Text>`

Final code:
```
let views = [1, 2, 3]
let style =
  Style.[
    fontSize(20),
    fontFamily("Roboto-Regular.ttf"),
  ];
let v = i => <View><Text style=style text=string_of_int(i) /></View>;
let myBeautifulElement = <View>...(List.map(v, views))</View>;
```

Happy coding :)


For any other question: You can ask on [discord](https://discord.gg/4pxY5Cp) where we have channel for revery. You will have response more quickly or you can include the [reasonml discord](https://discord.gg/reasonml)

**Comment by Et7f3** [comment]
Ok some error.
- To have self closing element we have to put the salsh at the end like normal HTML.
`</View>` => `<View/>`
- Also the function v take unit `()` it won't magically render what you want.
`let v = ()` => `let v = i`
- You have used iter instead of map: you want to generate a new list from the first one.
`List.iter(v, views)` => `List.map(v, views)`
- Then you have a list of `React.syntheticElement`. One common way to convert `list(React.syntheticElement)` =>`React.syntheticElement` is to wrap with a View component. Like this `(List.map(v, views))` => `<View>...(List.map(v, views))</View>`
You may notice `</View>` because here it is not a self-closing element: it is a end tag. The syntax follow the HTML one. It is called JSX.
- So here we have 3 views. We want to have contente inside we will fix the v function
`let v = i => </View/>;` =>
```
let style =
  Style.[
    fontSize(20),
    fontFamily("Roboto-Regular.ttf"),
  ];
  let v = i => <View><Text style=style text="Hellow world"></Text></View>;
```
We have to put some font: in the future we will auto-detect font available. One feature of reason is `style=style` => `style` the shortcut is valid only if it is the same name.
- now simply use the valeur of `v`
`<Text style=style text="Hellow world"></Text>` => `<Text style=style text=string_of_int(i)></Text>`

Final code:
```
let views = [1, 2, 3]
let style =
  Style.[
    fontSize(20),
    fontFamily("Roboto-Regular.ttf"),
  ];
let v = i => <View><Text style=style text=string_of_int(i) /></View>;
let myBeautifulElement = <View>...(List.map(v, views))</View>;
```

Happy coding @TrakBit :)

For any other question: You can ask on [discord](https://discord.gg/4pxY5Cp) where we have channel for revery. You will have response more quickly or you can include the [reasonml discord](https://discord.gg/reasonml)

**Comment by TrakBit** [comment]
@Et7f3 thank you so much for the detailed help :-)

**Comment by Et7f3** [comment]
See you on Discord 😉.

**Comment by richarddewit** [comment]
Apparently this changed in the meantime. When I did this, I got this error:

```
This type doesn't match what is expected.

  This type:
    list(Brisk_reconciler.element(Revery_UI.node))

  Expecting:
    Revery_UI.React.React.element(Revery_UI.React.node)
    Equals
    Brisk_reconciler.element(Revery_UI.React.node)

```

I did some fiddling and changed to `React.listToElement`:

```reason
// Old
let myBeautifulElement = <View>...(List.map(v, views))</View>;
// New
let myBeautifulElement = <View> {React.listToElement(List.map(v, views))} </View>;
```

**Comment by Et7f3** [comment]
Yeah sorry about that it when we have updated Briisk_reconciler.
