### ISSUE TITLE
`esy-skia` fails to build on Manjaro

### ISSUE THREAD

**Issue by glennsl** [revery-ui/revery#721]
`esy skia` requires two additional manual dependencies, `nasm` and `clang`. Manjaro packages clang 9, which unfortunately fails to build `skia` with the following error:

```
    ../../src/gpu/ops/GrOp.h:148:37: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
            TRACE_EVENT0("skia", name());
```

This is because `-Werror` is on and clang 8+ includes a new warning, `extra-semi-stmt`.

I've tried installing clang 7, but that's installed side-by-side and unfortunately esy does not seem to respect the `CC` and `CXX` environment variables.

**Comment by bryphe** [comment]
Unfortunately I lost my Manjaro box, so I can't repro at the moment.

The place we'd want to look to fix it is here:
https://github.com/revery-ui/esy-skia/blob/4e72dea73f031bb54b0e457fd73e0898358cd4bb/esy/build.sh#L29

(And it should reproduce by just building the `esy-skia` project).

Trying to see if I can add a build configuration w/ clang 9 to reproduce / protect as well.

A couple possible fixes:
- We could add a way to specify the clang executable for `esy-skia` - like `ESY_SKIA_C`/`ESY_SKIA_CXX` variables, that would take precedence over the other logic we have in the script
- If the warning is the only issue - maybe we can add a `-Wnoextra-semi-stmt`, or turn `-Werror` off? We're not changing the C code, so `-Werror` doesn't really do anything for us anyway right now...

I don't think setting the `CC` and `CXX` will work, because we actually have different `CC` and `CXX` depending on the environment - for most of the OCaml toolchain, we use `gcc` and `g++`, but for skia, we use `clang`.

**Comment by bryphe** [comment]
Looks like the `-Werror` flag is added here:
https://github.com/revery-ui/esy-skia/blob/4e72dea73f031bb54b0e457fd73e0898358cd4bb/gn/BUILD.gn#L357

Might be worth trying a build with that removed - just to see if that is the only issue, or if there are others.
